### ISSUE TITLE
E3D hotend support not fit in the elbow top/bottom plates

### ISSUE THREAD

**Issue by sl1pkn07** [madl3x/x-scara#2]
![photo_2020-11-13_20-36-09](https://user-images.githubusercontent.com/462213/99113730-061ee980-25f0-11eb-83d9-677307ffa5a1.jpg)
![photo_2020-11-13_20-36-10 (2)](https://user-images.githubusercontent.com/462213/99113734-08814380-25f0-11eb-978c-b454cd409a52.jpg)
![photo_2020-11-13_20-36-10](https://user-images.githubusercontent.com/462213/99113740-09b27080-25f0-11eb-8706-09f3458174b3.jpg)

**Comment by madl3x** [comment]
Thank you, your reported issue is correct. There is an overlap of 1.61 mm between the parts.
I will fix it and update the STL and .f3d files. Until then please just trim your part or cut the STL with an editor, so you can finish the assembly.

**Comment by sl1pkn07** [comment]
thanks, but i don't have hurry at all, the frame prefix and the most mechanic parts is still on transit (ETA end of november or start of december)

so take you time

greetings
