### ISSUE TITLE
Typo in the Frame_Plate_SideConnector piece

### ISSUE THREAD

**Issue by sl1pkn07** [madl3x/x-scara#3]
![image](https://user-images.githubusercontent.com/462213/98485841-9688b300-2219-11eb-8dd5-73abef611687.png)
 K -> C

greetings

**Comment by sl1pkn07** [comment]
Hi

for print this piece, in the right side, is needed to print it in mirror mode, but the text is also morrored

![photo_2020-11-21_17-05-07](https://user-images.githubusercontent.com/462213/99881775-0d5f7c00-2c1c-11eb-8bf4-baaff4bd0985.jpg)
![photo_2020-11-21_17-05-10](https://user-images.githubusercontent.com/462213/99881758-ee60ea00-2c1b-11eb-8fd9-be32e0546c2b.jpg)

for look&feel better, i think this piede needs to be added in the piece list a mirrored piece but with thext in the rigth position

what you think?

greetings

**Comment by madl3x** [comment]
Fixed typo. Added two separate versions (left and right) for the side connectors. Thank you for noticing.
