### ISSUE TITLE
Missing download button!

### ISSUE THREAD

**Issue by alassedy** [madl3x/x-scara#5]
Hi,
I tried to download the Fusion 360 version of your design, but I couldn't find the download button for the arm assembly when opened this link:
https://a360.co/2YkuguU
Unlike the frame assembly like which has the download button.
Thank you for the great design.

**Comment by madl3x** [comment]
I'll verify that, but you can download the STLs from Github or Thingiverse. Check out the releases section.

**Comment by jschilli** [comment]
is it possible to allow downloads of the arm models?  The 'allow item to be downloaded' switch needs to be on in Fusion when sharing the link.

I'm looking to model new end effectors on the arm and it would be helpful to evolve your model vs starting from scratch.

Great project!
